#######################
# Setup Configuration #
#######################

[metadata]
name = modelSelector
version = attr: modelSelector.version.__version__
description = Model Selection for AIC/BIC/AICc/... via various selection methods
long_description = file: README.md
long_description_content_type = text/markdown

# URLs
url = TBD
download_url = TBD
project_urls =
    Bug Tracker = TBD/issues
    Documentation = TBD
    Changelog = TBD

# Author information
author = The modelSelector developers
author_email = TBD
maintainer = Jakob Vanhoefer, Dilan Pathirana
maintainer_email = TBD

# License information
license = BSD-3-Clause
license_files = LICENSE

# Search tags
classifiers =
    Development Status :: 4 - Beta
    License :: OSI Approved :: BSD License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.9
keywords =
    model selection
    AIC
    BIC

[options]
install_requires =
    numpy >= 1.19.1
    pandas >= 1.5.0

python_requires = >=3.9
include_package_data = True

# Where is my code
packages = find:

[options.packages.find]
include = modelSelector*

[options.extras_require]
test =
    pytest >= 5.4.3
    pytest-cov >= 2.10.0
    gitpython >= 3.1.7
    pytest-rerunfailures >= 9.1.1
    autograd >= 1.3

[bdist_wheel]
# Requires Python 3
universal = False
